/*
 * DIO_Confg.c
 *
 *  Created on: Dec 24, 2021
 *      Author: Samaa Seif
 */
#include"DIO_Confg.h"

DIO_ENU_PIN_STATE DIO_PIN_CONFG[PINS_NO]=
{	OUTPUT,    // PORTA0
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT, //PORTB0
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	INPUT_PULLUP,   // PORTC0
	INPUT_PULLUP,
	INPUT_PULLUP,
	INPUT_PULLUP,
	OUTPUT,         // PORTC4
	OUTPUT,
	OUTPUT,
	OUTPUT,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING
};

