/*
 * KEYPAD.c
 *
 *  Created on: Dec 23, 2021
 *      Author: Samaa Seif
 */
#include"STD_Types.h"
#include"DIO.h"
#include"DIO_CONFIG.h"
#include"BIT_MATH.h"
#include"SEV_SEG.h"
#include"SWITCH.h"
#include"KEYPAD.h"

void KEYPAD_INIT(void) {
	DIO_INIT_PORT_DIRECTION(KEYPAD_PORT, 0xF0);
	DIO_WRITE_PORT_VALUE(KEYPAD_PORT, 0x0F);
}

uint8 KEYPAD_READ(void)
{
	uint8  Value=NO_PRESSED_VALUE;
	uint8  KEYPAD_ROW_INDEX, KEYPAD_COLUMN_INDEX,KEYPAD_Pin_State;
	uint8 KEYPAD_ARR[KEYOAD_ROW_IND3][KEYOAD_COL_IND3]= KEYPAD_KEYS_3x3;
	uint8 KEYPAD_ROW_PinArr[3]={KEYPAD_ROW0, KEYPAD_ROW1,KEYPAD_ROW2};
	uint8 KEYPAD_COL_PinArr[3]={KEYPAD_COLUMN0,KEYPAD_COLUMN1,KEYPAD_COLUMN2};
	for(KEYPAD_COLUMN_INDEX=0; KEYPAD_COLUMN_INDEX<KEYOAD_COL_IND3; KEYPAD_COLUMN_INDEX++)
		{
		DIO_WRITE_PIN_VALUE(KEYPAD_PORT, KEYPAD_COL_PinArr[KEYPAD_COLUMN_INDEX], LOW);
			for(KEYPAD_ROW_INDEX=0; KEYPAD_ROW_INDEX<KEYOAD_ROW_IND3; KEYPAD_ROW_INDEX++)
			{
				KEYPAD_Pin_State = DIO_READ_PIN_VALUE(KEYPAD_PORT,KEYPAD_ROW_PinArr[KEYPAD_ROW_INDEX]);
				if(LOW == KEYPAD_Pin_State )
				{
					Value= KEYPAD_ARR[KEYPAD_ROW_INDEX][KEYPAD_COLUMN_INDEX];
					while(LOW == DIO_READ_PIN_VALUE(KEYPAD_PORT,KEYPAD_ROW_PinArr[KEYPAD_ROW_INDEX]));
					//DIO_WRITE_PIN_VALUE(KEYPAD_PORT, KEYPAD_COL_PinArr[KEYPAD_COLUMN_INDEX],HIGH);
					//return Value;
				}
			}
			DIO_WRITE_PIN_VALUE(KEYPAD_PORT, KEYPAD_COL_PinArr[KEYPAD_COLUMN_INDEX],HIGH);
		}
		return Value;
}
/*
uint8 KEYPAD_PRESSES_KEY(void)
{
	uint8  Value=NO_PRESSED_VALUE;
	uint8  KEYPAD_ROW_INDEX, KEYPAD_COLUMN_INDEX,KEYPAD_Pin_State;
	uint8 KEYPAD_ARR[KEYOAD_ROW_IND3][KEYOAD_COL_IND3]= KEYPAD_KEYS_3x3;
	uint8 KEYPAD_ROW_PinArr[KEYOAD_ROW_IND3]={KEYPAD_ROW0, KEYPAD_ROW1,KEYPAD_ROW2};
	uint8 KEYPAD_COL_PinArr[KEYOAD_COL_IND3]={KEYPAD_COLUMN0,KEYPAD_COLUMN1,KEYPAD_COLUMN2};
	for(KEYPAD_COLUMN_INDEX=0; KEYPAD_COLUMN_INDEX<KEYOAD_COL_IND3; KEYPAD_COLUMN_INDEX++)
		{
		DIO_WRITE_PIN_VALUE(KEYPAD_PORT, KEYPAD_COL_PinArr[KEYPAD_COLUMN_INDEX], LOW);
			for(KEYPAD_ROW_INDEX=0; KEYPAD_ROW_INDEX<KEYOAD_ROW_IND3; KEYPAD_ROW_INDEX++)
			{
				DIO_READ_PIN_VALUE(KEYPAD_PORT,KEYPAD_ROW_PinArr[KEYPAD_ROW_INDEX]);
				if(LOW == KEYPAD_Pin_State )
				{
					Value= KEYPAD_ARR[KEYPAD_ROW_INDEX][KEYPAD_COLUMN_INDEX];
					while(LOW == KEYPAD_Pin_State)
					{
						DIO_READ_PIN_VALUE(KEYPAD_PORT,KEYPAD_ROW_PinArr[KEYPAD_ROW_INDEX]);
					}
					return Value;
				}
			}
			DIO_WRITE_PIN_VALUE(KEYPAD_PORT, KEYPAD_COL_PinArr[KEYPAD_COLUMN_INDEX],HIGH);
		}
		return Value;
}


*/
