/*
 * DIO_Confg.c
 *
 *  Created on: Dec 24, 2021
 *      Author: Samaa Seif
 */
#include"DIO_Confg.h"

DIO_ENU_PIN_STATE DIO_PIN_CONFG[PINS_NO]=
{	OUTPUT,    // PORTA0
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,

	OUTPUT, //PORTB0
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,

	OUTPUT,   // PORTC0
	OUTPUT,
	OUTPUT,
	INPUT_FLOATING,         // PORTC4
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,

	INPUT_FLOATING,      //PORTD0
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING
};

