/*
 * DIO_Confg.c
 *
 *  Created on: Dec 24, 2021
 *      Author: Samaa Seif
 */
#include"DIO_Confg.h"

DIO_ENU_PIN_STATE DIO_PIN_CONFG[PINS_NO]=
{	INPUT_PULLUP, // PORTA0
	INPUT_PULLUP,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,

	OUTPUT, //PORTB0
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,
	OUTPUT,

	INPUT_FLOATING,   // PORTC0
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,   // PORTC4
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,

	OUTPUT,           //PORTD0
	INPUT_FLOATING,
	OUTPUT,
	OUTPUT,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING,
	INPUT_FLOATING
};

